window.MOMENT_IDEAS = [
  {
    id: "waiting-window-detectives",
    title: "Waiting-window detectives",
    category: "Calm + cosy",
    audience: ["sylvie", "elias", "together"],
    needs: ["calm", "together", "quick", "transition"],
    minutes: 5,
    where: "Waiting room, cafe, or parked car",
    setup: "No setup",
    summary: "Take turns spotting colours, shapes, movement, and tiny details through a window.",
    steps: ["Choose one thing to hunt for, such as circles or something moving.", "Each person spots one example.", "Finish with one final quiet find before it is time to move."],
    why: "A shared noticing game gives waiting time a predictable focus without needing supplies.",
    say: "\"Let's find three quiet clues, then we will be ready.\"",
    caution: "Only play in a safely parked car and keep supervision focused in public places.",
    source: "Family notes + practical expansion"
  },
  {
    id: "pocket-story-chain",
    title: "Pocket story chain",
    category: "Creative + curious",
    audience: ["sylvie", "together"],
    needs: ["creative", "calm", "together", "quick"],
    minutes: 5,
    where: "Waiting room, car, or table",
    setup: "No setup",
    summary: "Build a tiny spoken story one sentence at a time using things you can see.",
    steps: ["Choose a visible character or object.", "Take turns adding one short sentence.", "Give the story a clear ending after three or four turns."],
    why: "Short story turns support language, flexibility, and connection during unavoidable waits.",
    say: "\"Once there was a very brave... what can you see?\"",
    caution: "Keep the game optional and low-demand if waiting is already difficult.",
    source: "Family notes + practical expansion"
  },
  {
    id: "grocery-colour-helper",
    title: "Grocery colour helper",
    category: "Everyday rhythm",
    audience: ["sylvie", "elias", "together"],
    needs: ["together", "transition", "quick"],
    minutes: 8,
    where: "Grocery shop",
    setup: "Shopping list",
    summary: "Give one safe colour, counting, or spotting job during the grocery trip.",
    steps: ["Choose one job before entering, such as finding three green foods.", "Notice and count together without rushing.", "Mark the job finished before checkout."],
    why: "A bounded helper role makes an everyday outing more predictable and meaningful.",
    say: "\"Your job is to help us find three green foods, then the job is done.\"",
    caution: "Keep children beside the supervising adult and do not ask them to retrieve breakable items.",
    source: "Family notes + practical expansion"
  },
  {
    id: "restaurant-finger-maze",
    title: "Tabletop finger maze",
    category: "Calm + cosy",
    audience: ["sylvie", "elias", "together"],
    needs: ["calm", "quick", "transition"],
    minutes: 4,
    where: "Cafe or dining table",
    setup: "Finger + clear tabletop",
    summary: "Trace slow roads, loops, numbers, and shapes on the table for another person to follow.",
    steps: ["Draw an invisible road slowly with one finger.", "Let the other person follow or guess the shape.", "Finish with one road that leads to HOME."],
    why: "Slow visual tracking and shared attention can make table waiting feel calmer.",
    say: "\"Can your finger follow my quiet road all the way home?\"",
    caution: "Use a clean, safe table surface and keep hands away from hot food and drinks.",
    source: "Family notes + practical expansion"
  },
  {
    id: "doorway-strong-body-station",
    title: "Doorway strong-body station",
    category: "Sensory diet",
    audience: ["sylvie", "together"],
    needs: ["move", "calm", "transition", "quick", "after-screen"],
    minutes: 3,
    where: "Clear doorway or hallway",
    setup: "No setup",
    summary: "Pause at a doorway for wall pushes, strong hands, and a clear next-step cue.",
    steps: ["Place both hands safely on the wall beside the doorway.", "Do five slow pushes while counting.", "Name the next place, then walk through together."],
    why: "Brief pushing gives strong body feedback and turns a doorway into a repeatable transition cue.",
    say: "\"Five strong pushes, then our body knows where we are going.\"",
    caution: "Use a stable clear wall, keep fingers away from hinges, and stop if uncomfortable.",
    source: "OT sensory diet + practical expansion"
  },
  {
    id: "sock-match-delivery",
    title: "Sock-match delivery",
    category: "Everyday rhythm",
    audience: ["sylvie", "elias", "together"],
    needs: ["move", "together", "transition", "quick"],
    minutes: 8,
    where: "Laundry area and bedrooms",
    setup: "Clean socks",
    summary: "Match clean socks, then carry each pair on a short delivery route.",
    steps: ["Make a small pile of clean socks.", "Find pairs together.", "Carry or push each pair to its home and announce the last delivery."],
    why: "Matching adds thinking while carrying and delivering make pack-away active and useful.",
    say: "\"Which socks belong together, and where is their home?\"",
    caution: "Keep the walking route clear and use only clean, dry laundry.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "dinner-job-cards",
    title: "Two dinner helper jobs",
    category: "Everyday rhythm",
    audience: ["sylvie", "elias", "together"],
    needs: ["together", "transition", "calm", "quick"],
    minutes: 5,
    where: "Kitchen and dining table",
    setup: "Two safe table jobs",
    summary: "Offer two concrete helper choices that end with everyone ready at the table.",
    steps: ["Name two safe jobs, such as napkin delivery or carrying placemats.", "Let each child choose or share one job.", "Announce the final delivery and sit together."],
    why: "Real jobs add movement, belonging, and a visible finish to the pre-dinner transition.",
    say: "\"Napkins or placemats? Your last delivery lands at the table.\"",
    caution: "Keep children away from hot, sharp, heavy, or breakable kitchen items.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "bath-wall-water-pictures",
    title: "Bath-wall water pictures",
    category: "Creative + curious",
    audience: ["sylvie", "together"],
    needs: ["creative", "calm", "transition"],
    minutes: 8,
    where: "Bath",
    setup: "Cup + bath water",
    summary: "Use a wet finger or cup of water to make temporary shapes and pictures on the bath wall.",
    steps: ["Dip a finger in bath water and draw one large shape.", "Take turns guessing or adding to it.", "Make the last picture a moon, star, or sleepy face before washing finishes."],
    why: "Temporary drawing adds calm creativity without another cleanup job.",
    say: "\"What picture can the water make before it disappears?\"",
    caution: "Follow normal close bath supervision and avoid splashing faces.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "bedtime-body-map",
    title: "Bedtime body map",
    category: "Calm + cosy",
    audience: ["sylvie"],
    needs: ["calm", "transition"],
    minutes: 5,
    where: "Bedtime",
    setup: "Blanket",
    summary: "Name and gently notice body parts from feet to head as the day finishes.",
    steps: ["Begin at the feet and notice whether they feel busy, warm, or still.", "Move slowly through legs, hands, shoulders, and face.", "Finish with one comfortable breath and the same goodnight phrase."],
    why: "A predictable body check can support body awareness and a gentle bedtime landing.",
    say: "\"Your feet are finished for today. Now your hands can rest too.\"",
    caution: "Keep touch optional and stop any part that feels uncomfortable.",
    source: "Family notes + practical expansion"
  },
  {
    id: "rainy-window-weather-station",
    title: "Rainy-window weather station",
    category: "Creative + curious",
    audience: ["sylvie", "elias", "together"],
    needs: ["creative", "calm", "together", "quick"],
    minutes: 8,
    where: "Window",
    setup: "Paper + pencil optional",
    summary: "Watch the weather, make a simple forecast, and choose one thing to notice again later.",
    steps: ["Look for cloud colour, wind, rain, and moving trees.", "Make a playful forecast for the next hour.", "Draw or remember one detail to check later."],
    why: "Weather watching turns an indoor day into real observation and prediction.",
    say: "\"What clues is the sky giving our weather station?\"",
    caution: "Observe from a secure indoor window and keep furniture away from open windows.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "hallway-tape-rescue-road",
    title: "Hallway rescue road",
    category: "Together",
    audience: ["sylvie", "elias", "together"],
    needs: ["move", "together", "creative", "after-screen"],
    minutes: 12,
    where: "Hallway or living room",
    setup: "Low-tack tape + toy vehicles",
    summary: "Make a short floor road with delivery stops and one rescue destination.",
    steps: ["An adult lays a simple low-tack road on a suitable floor.", "Choose two delivery stops and one rescue point.", "Drive the route, complete the rescue, and peel up the road together."],
    why: "The road gives sibling play a shared structure and a clear cleanup ending.",
    say: "\"Which stop needs a delivery, and where is the rescue?\"",
    caution: "Adult handles tape, tests the floor first, and keeps the road away from walking hazards.",
    source: "Family notes + practical expansion"
  },
  {
    id: "freeze-and-melt-dance",
    title: "Freeze and melt dance",
    category: "Sensory diet",
    audience: ["sylvie", "elias", "together"],
    needs: ["move", "calm", "together", "quick", "after-screen"],
    minutes: 6,
    where: "Living room or backyard",
    setup: "Clear space",
    summary: "Alternate lively movement with slow melting to practise changing body speed.",
    steps: ["Dance or move freely for a short burst.", "Call FREEZE, then slowly melt down toward the floor.", "Repeat a few times and make the final melt the finish."],
    why: "Changing from fast to slow practises inhibition and helps movement end predictably.",
    say: "\"Fast body, freeze body, now melt all the way to finished.\"",
    caution: "Clear the movement space and keep floor movements comfortable and safe.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "sibling-mail-delivery",
    title: "Sibling mail delivery",
    category: "Together",
    audience: ["sylvie", "elias", "together"],
    needs: ["together", "creative", "move", "quick"],
    minutes: 8,
    where: "Home",
    setup: "Paper + pencil",
    summary: "Draw tiny messages, then give each child a protected delivery job.",
    steps: ["Draw one simple picture-message for each person.", "Choose a safe mailbox spot.", "Take turns delivering, receiving, and saying thank you."],
    why: "Separate sender and delivery roles support connection without demanding identical play.",
    say: "\"This message needs a careful delivery helper. Which mailbox is first?\"",
    caution: "Use large paper pieces and supervise drawing tools around Elias.",
    source: "Family sibling strategy + practical expansion"
  },
  {
    id: "toy-wash-station",
    title: "Toy wash station",
    category: "Everyday rhythm",
    audience: ["sylvie", "elias", "together"],
    needs: ["calm", "together", "creative", "transition"],
    minutes: 12,
    where: "Outdoor table, sink, or bath",
    setup: "Shallow water + washable toys + towel",
    summary: "Wash a small set of waterproof toys, then dry and return each one home.",
    steps: ["Choose a small set of known waterproof toys.", "Wash, rinse, and line them up on a towel.", "Dry each toy and make the last return together."],
    why: "Water play, sequencing, and a real cleanup job create an absorbing shared rhythm.",
    say: "\"Which toy is first, and which one will be our last clean delivery?\"",
    caution: "Directly supervise all water play and use only toys known to be waterproof and age-appropriate.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "chalk-feelings-path",
    title: "Chalk feelings path",
    category: "Outdoor",
    audience: ["sylvie", "together"],
    needs: ["outside", "move", "creative", "calm"],
    minutes: 12,
    where: "Driveway or path",
    setup: "Chalk",
    summary: "Draw simple feeling faces along a path, then move between them in matching ways.",
    steps: ["Draw three or four large feeling faces.", "Move to each face and name or act out its feeling.", "Choose a calm or proud face as the finish."],
    why: "Movement makes emotion language playful and less demanding.",
    say: "\"How might our feet move to the excited face? Where should we finish?\"",
    caution: "Use a traffic-free, non-slip area and do not pressure children to discuss feelings.",
    source: "Family notes + practical expansion"
  },
  {
    id: "sound-detective-walk",
    title: "Sound detective walk",
    category: "Outdoor",
    audience: ["sylvie", "elias", "together"],
    needs: ["outside", "calm", "together", "quick"],
    minutes: 10,
    where: "Backyard, park, or neighbourhood",
    setup: "No setup",
    summary: "Walk slowly, pause at three spots, and identify near, far, loud, or quiet sounds.",
    steps: ["Choose a short familiar route.", "Pause at three safe spots and listen.", "Pick one favourite sound, then return home."],
    why: "Focused listening can make outdoor time calming while building language and attention.",
    say: "\"Detectives, what sound is near us and what sound is far away?\"",
    caution: "Use normal outdoor supervision and leave noisy places if they become uncomfortable.",
    source: "Home-Based Enrichment Program + practical expansion"
  },
  {
    id: "shadow-copy-chase",
    title: "Shadow copy chase",
    category: "Outdoor",
    audience: ["sylvie", "elias", "together"],
    needs: ["outside", "move", "together", "quick"],
    minutes: 8,
    where: "Backyard or park",
    setup: "Sunlight + clear space",
    summary: "Make shapes with shadows, copy each other, and try to touch a shadow without touching bodies.",
    steps: ["Find a clear sunny patch.", "Take turns making one shadow shape or movement.", "Finish by waving the shadows goodbye."],
    why: "Shadow play adds imagination and shared attention to simple outdoor movement.",
    say: "\"Can your shadow copy mine without our bodies touching?\"",
    caution: "Use a clear area, avoid looking at the sun, and keep bodies safely spaced.",
    source: "Outdoor play research + practical expansion"
  },
  {
    id: "nature-potion-lab",
    title: "Nature potion lab",
    category: "Outdoor",
    audience: ["sylvie", "elias", "together"],
    needs: ["outside", "creative", "calm", "together"],
    minutes: 15,
    where: "Backyard",
    setup: "Container + water + safe fallen nature items",
    summary: "Mix water with safe fallen leaves, petals, and sticks to invent a pretend nature potion.",
    steps: ["Collect a few known safe fallen items.", "Add them to water and stir with a stick.", "Name the pretend potion, pour it onto the garden, and return the container."],
    why: "Open-ended outdoor mixing supports sensory exploration, imagination, and a natural finish.",
    say: "\"What is your pretend potion called, and which plant gets the last pour?\"",
    caution: "Directly supervise water; do not taste ingredients; avoid unknown, irritating, or toxic plants.",
    source: "Outdoor play research + practical expansion"
  },
  {
    id: "puddle-target-walk",
    title: "Puddle target walk",
    category: "Outdoor",
    audience: ["sylvie", "together"],
    needs: ["outside", "move", "transition"],
    minutes: 12,
    where: "Safe path after rain",
    setup: "Weather-ready clothes",
    summary: "Choose a few safe puddles or wet landmarks and travel between them with different steps.",
    steps: ["Choose a short route and clear turn-around point.", "Tiptoe, stomp, or march between safe wet landmarks.", "Use the final puddle as the cue to head home."],
    why: "A bounded wet-weather mission makes movement inviting and the return predictable.",
    say: "\"Three puddle stops, then the last splash sends us home.\"",
    caution: "Avoid roads, drains, deep or contaminated water, slippery surfaces, and storms.",
    source: "Outdoor play research + practical expansion"
  },
  {
    id: "five-minute-backyard-reset",
    title: "Five-minute backyard reset",
    category: "Outdoor",
    audience: ["sylvie", "elias", "together"],
    needs: ["outside", "move", "calm", "quick", "transition", "after-screen"],
    minutes: 5,
    where: "Backyard",
    setup: "No setup",
    summary: "Step outside for one lap, one strong job, and one quiet noticing moment.",
    steps: ["Walk one familiar backyard lap.", "Push, carry, or move one safe outdoor item.", "Notice one sky, plant, or weather detail, then go back in."],
    why: "A tiny repeatable outdoor rhythm can reset the moment without becoming another large activity.",
    say: "\"One lap, one strong job, one thing to notice, then inside.\"",
    caution: "Use normal outdoor supervision and choose only safe, manageable carrying jobs.",
    source: "Family notes + practical expansion"
  }
];
